default:
    @echo "Android commands:"
    @just --list

# regeneruje gradle wrapper
wrapper:
    gradle wrapper --gradle-version 9.4.1

# checker
lint:
    ./gradlew ktlintCheck

# formatuj
format:
    ./gradlew ktlintFormat

# pełny build
build:
    ./gradlew clean build

# debug build
assemble:
    ./gradlew assembleDebug

# reinstall new built application on already running emulator instance
reinstall:
    adb install -r app/build/outputs/apk/debug/app-debug.apk
